### ISSUE TITLE
Hi, Ed!

### ISSUE THREAD

**Issue by gmile** [TheSignPainter98/emblem#98]
I failed to find the contacts info on your personal site, so I figured I'd open an issue to reach out :) Following our convo during dinner in Zagreb, I remembered one TeX-related project I wanted to share with you, but couldn't remember it's name back then.

The project is: https://github.com/tectonic-typesetting/tectonic

I subscribed to the new releases, and just got a notification that they cut a new release.

Strictly speaking it's not related to the kind of goals you have with Emblem, it could just be treated as a point of reference, I guess.

Feel free to remove this issue once you receive this message 🙇

**Comment by TheSignPainter98** [comment]
Hey Ievgen! This seems like an oversight, I'll pop some contact details on there when I get a moment, probably just Linkedin and my email, ed@kcza.net

Ah yes, I remember you mentioning Tectonic! (Although not by name haha) It looks very promising, reproducible builds are something which I've had troubles with when using LaTeX in the past, so this'll really help with maintaining my existing documents! It feels like this property and the ability to download packages lazily are things I should definitely try to achieve with Emblem... 🤔 

Following dinner in Zagreb, I actually made the switch to Wezterm and nvim, really liking the possibilities opened up by using Lua as a configuration language! With a small amount of trickery I also managed to write the config using [yuescript](https://github.com/pigpigyyy/Yuescript), cleaning things up nicely 🎉
